version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: albi123
      POSTGRES_DB: DB_tranning
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: albi123
      DB_NAME: DB_tranning
